version: '3.8'

services:
  # Backend API
  backend:
    image: ${BACKEND_IMAGE:-uscola-backend}
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FRONTEND_URL=http://localhost:5173
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - uscola-network

  # Frontend
  frontend:
    image: ${FRONTEND_IMAGE:-uscola-frontend}
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:3000
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - uscola-network

  # Optional: Database (if needed later)
  # database:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: uscola
  #     POSTGRES_USER: uscola
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - uscola-network

networks:
  uscola-network:
    driver: bridge

# volumes:
#   postgres_data: